import type { Recommendation } from "@/lib/types";

export const demoOfferRecommendation = {
  current_monthly_spend_eur: 435,
  best: {
    scenario_id: "full-bundle",
    label: "Solar + Battery + Heat pump + EV charger",
    breakdown: {
      electricity_eur_month: 124,
      heating_eur_month: 106,
      mobility_eur_month: 134,
    },
    capex: {
      gross_eur: 42000,
      subsidy_eur: 11000,
      after_subsidy_eur: 31000,
      subsidy_note: "EUR 22k HP - 50% KfW 458 = EUR 11k; PV/battery 0% VAT",
    },
    installment_eur_month: 244,
    monthly_saving_eur: 120,
    saving_after_payoff_eur: 364,
    break_even_month: 156,
    confidence: {
      band_eur: 35,
      low_eur: 85,
      high_eur: 155,
      biggest_driver: "self-consumption ratio",
    },
    payback_note: "EUR 120/mo from day one; EV is the biggest single contributor",
  },
  alternatives: [
    {
      scenario_id: "pv-only",
      label: "Solar 9 kWp",
      breakdown: {
        electricity_eur_month: 80,
        heating_eur_month: 0,
        mobility_eur_month: 0,
      },
      capex: {
        gross_eur: 13050,
        subsidy_eur: 0,
        after_subsidy_eur: 13050,
        subsidy_note: "0% VAT",
      },
      installment_eur_month: 103,
      monthly_saving_eur: -24,
      saving_after_payoff_eur: 80,
      break_even_month: 180,
      confidence: {
        band_eur: 15,
        low_eur: -39,
        high_eur: -9,
        biggest_driver: "local irradiance",
      },
      payback_note: "Mildly negative until loads are electrified.",
    },
    {
      scenario_id: "pv-battery",
      label: "Solar + Battery 8 kWh",
      breakdown: {
        electricity_eur_month: 124,
        heating_eur_month: 0,
        mobility_eur_month: 0,
      },
      capex: {
        gross_eur: 18650,
        subsidy_eur: 0,
        after_subsidy_eur: 18650,
        subsidy_note: "0% VAT",
      },
      installment_eur_month: 147,
      monthly_saving_eur: -24,
      saving_after_payoff_eur: 124,
      break_even_month: 180,
      confidence: {
        band_eur: 20,
        low_eur: -44,
        high_eur: -4,
        biggest_driver: "dynamic tariff spread",
      },
      payback_note: "Battery value unlocks when HP and EV add load.",
    },
    {
      scenario_id: "pv-battery-hp",
      label: "Solar + Battery + Heat pump",
      breakdown: {
        electricity_eur_month: 124,
        heating_eur_month: 106,
        mobility_eur_month: 0,
      },
      capex: {
        gross_eur: 29650,
        subsidy_eur: 11000,
        after_subsidy_eur: 18650,
        subsidy_note: "HP: EUR 22k - 50% KfW 458; PV+battery 0% VAT",
      },
      installment_eur_month: 234,
      monthly_saving_eur: -4,
      saving_after_payoff_eur: 230,
      break_even_month: 178,
      confidence: {
        band_eur: 25,
        low_eur: -29,
        high_eur: 21,
        biggest_driver: "KfW subsidy rate",
      },
      payback_note: "Near break-even; heat pump displaces oil spend.",
    },
    {
      scenario_id: "full-bundle",
      label: "Solar + Battery + Heat pump + EV charger",
      breakdown: {
        electricity_eur_month: 124,
        heating_eur_month: 106,
        mobility_eur_month: 134,
      },
      capex: {
        gross_eur: 42000,
        subsidy_eur: 11000,
        after_subsidy_eur: 31000,
        subsidy_note: "EUR 22k HP - 50% KfW 458 = EUR 11k; PV/battery 0% VAT",
      },
      installment_eur_month: 244,
      monthly_saving_eur: 120,
      saving_after_payoff_eur: 364,
      break_even_month: 156,
      confidence: {
        band_eur: 35,
        low_eur: 85,
        high_eur: 155,
        biggest_driver: "self-consumption ratio",
      },
      payback_note: "EUR 120/mo from day one; EV is the biggest single contributor",
    },
  ],
  tiers: [
    {
      id: "low",
      name: "Entry",
      tagline: "Lowest starting investment with a clear upgrade path.",
      scenario_id: "pv-only",
      label: "Solar 9 kWp",
      capex_after_subsidy_eur: 13050,
      installment_eur_month: 103,
      monthly_saving_eur: -24,
      saving_after_payoff_eur: 80,
      break_even_month: 180,
      lifetime_years: 20,
      lifetime_saving_eur: 480,
      headline_eur: 80,
      headline_caption: "EUR/month after payoff",
      rationale_md:
        "The lightest commitment: EUR 13,050 net capex and EUR 103/month financing. It is the cautious first step before electrifying heating and mobility.",
    },
    {
      id: "middle",
      name: "Best value",
      tagline: "The strongest balance of investment and permanent saving.",
      scenario_id: "pv-battery-hp",
      label: "Solar + Battery + Heat pump",
      capex_after_subsidy_eur: 18650,
      installment_eur_month: 234,
      monthly_saving_eur: -4,
      saving_after_payoff_eur: 230,
      break_even_month: 178,
      lifetime_years: 20,
      lifetime_saving_eur: 13080,
      headline_eur: 230,
      headline_caption: "EUR/month after payoff",
      rationale_md:
        "Best value for a homeowner who wants the big fixed-cost reduction without adding mobility yet. The heat pump makes the solar and battery package work harder.",
    },
    {
      id: "high",
      name: "Future-proof",
      tagline: "Maximum long-term upside across power, heat, and mobility.",
      scenario_id: "full-bundle",
      label: "Solar + Battery + Heat pump + EV charger",
      capex_after_subsidy_eur: 31000,
      installment_eur_month: 244,
      monthly_saving_eur: 120,
      saving_after_payoff_eur: 364,
      break_even_month: 156,
      lifetime_years: 20,
      lifetime_saving_eur: 43440,
      headline_eur: 43440,
      headline_caption: "over 20 years",
      rationale_md:
        "The complete package is the first option that saves from day one. It turns petrol, oil, and grid exposure into one financed energy upgrade.",
    },
  ],
  upsell: {
    from_scenario_id: "pv-battery",
    to_scenario_id: "full-bundle",
    delta_eur_month: 144,
    reason_md:
      "Going from PV+battery to the full bundle lands +EUR 120/mo because oil and petrol are still the costly parts of the household budget.",
  },
  explanation_md:
    "This home is best served by the full package: the heat pump replaces oil spend, the EV charger makes mobility cheaper, and solar plus battery increase self-consumption.",
  proposal_copy_md:
    "Your personal Heimwende energy plan: with solar, battery, heat pump, and wallbox, the household saves EUR 120/mo from day one and EUR 364/mo after financing ends.",
  assumptions: [
    {
      field: "specific_yield_kwh_per_kwp",
      value: "980 kWh/kWp",
      source: "PVGIS fallback",
      editable: true,
    },
    {
      field: "kfw_subsidy_rate",
      value: "50%",
      source: "KfW 458 base and speed bonus",
      editable: true,
    },
    {
      field: "financing_term_months",
      value: "180 months",
      source: "Demo financing assumption",
      editable: true,
    },
  ],
} satisfies Recommendation;
