import {
  ArrowLeft,
  BadgeEuro,
  BatteryCharging,
  ChevronDown,
  ChevronRight,
  Database,
  Download,
  Flame,
  Globe2,
  ListChecks,
  Loader2,
  MapPin,
  PlugZap,
  ShieldCheck,
  Sparkles,
  Sun,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState, type ReactNode } from "react";
import type { Assumption, Recommendation, ScenarioResult, Tier } from "@/lib/types";
import {
  groupEventsByStage,
  type ActivityEvent,
  type PipelineRunState,
  type StageGroup,
} from "@/features/activity/pipeline";
import HeimwendeMark from "@/components/HeimwendeMark";
import { postReport } from "@/lib/api";

/* A real letter wants a real date. Formatted once per render — this is prose
   chrome, never a figure the math depends on. */
const LETTER_DATE = new Date().toLocaleDateString("en-GB", {
  day: "numeric",
  month: "long",
  year: "numeric",
});

/* A script face for the sign-off flourish. Pure brand chrome with a graceful
   cursive fallback on every platform — no font dependency added. */
const SIGNATURE_FONT =
  "'Snell Roundhand', 'Segoe Script', 'Brush Script MT', 'Apple Chancery', cursive";

/* An editorial serif for the advisor letter body so it reads like a real
   piece of correspondence, not UI chrome. System serifs only — no web font
   dependency added. */
const LETTER_FONT =
  "'Iowan Old Style', 'Palatino Linotype', 'Palatino', 'Book Antiqua', Georgia, 'Times New Roman', serif";

/* Restrained palette — the blue accent + neutral slates, with green for
   positive savings and a calm amber for negative. One deep-slate "dark
   moment" lives in the footer; everything else stays light and airy. */
const EASE = "ease-[cubic-bezier(0.23,1,0.32,1)]";

function eur(n: number, opts?: { sign?: boolean; compact?: boolean }) {
  const abs = Math.abs(n);
  const formatted = abs.toLocaleString("de-DE", {
    maximumFractionDigits: 0,
    notation: opts?.compact ? "compact" : "standard",
  });
  if (opts?.sign) return `${n >= 0 ? "+" : "-"}€${formatted}`;
  return `${n < 0 ? "-" : ""}€${formatted}`;
}

function clean(value: string) {
  return value
    .replace(/[*_`]/g, "") // strip leftover markdown emphasis
    .replace(/[\u{FE0F}\u{200D}]/gu, "")
    .replace(/\p{Extended_Pictographic}/gu, "") // strip emoji
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, " ")
    .trim();
}

/* Strip the noise the LLM prose can carry (emoji, stray backticks/underscores)
   without touching the bold/italic emphasis markers we actually want to render. */
function tidy(value: string) {
  return value
    .replace(/[`_]/g, "")
    .replace(/[\u{FE0F}\u{200D}]/gu, "")
    .replace(/\p{Extended_Pictographic}/gu, "")
    .trim();
}

/* Render one line of inline markdown: **bold** and *italic*. No dependency
   added — the advisor prose only ever uses these two markers. */
function inline(text: string, keyBase: string): ReactNode[] {
  const out: ReactNode[] = [];
  const re = /\*\*(.+?)\*\*|\*(.+?)\*/g;
  let last = 0;
  let match: RegExpExecArray | null;
  let i = 0;
  while ((match = re.exec(text)) !== null) {
    if (match.index > last) out.push(text.slice(last, match.index));
    if (match[1] !== undefined) {
      out.push(
        <strong key={`${keyBase}-${i}`} className="font-semibold text-[#0f172a]">
          {match[1]}
        </strong>,
      );
    } else {
      out.push(<em key={`${keyBase}-${i}`}>{match[2]}</em>);
    }
    last = match.index + match[0].length;
    i += 1;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

/* Minimal markdown → paragraphs for the advisor letter: blank lines split
   paragraphs, single newlines collapse, bold and italic render inline. */
function Markdown({ children, className }: { children: string; className?: string }) {
  const paragraphs = tidy(children)
    .split(/\n{2,}/)
    .map((p) => p.replace(/\s*\n\s*/g, " ").trim())
    .filter(Boolean);
  return (
    <div className={className}>
      {paragraphs.map((p, idx) => (
        <p key={idx}>{inline(p, `p${idx}`)}</p>
      ))}
    </div>
  );
}

function AiBadge({ className = "" }: { className?: string }) {
  return (
    <span
      title="Generated by the Heimwende AI advisor — figures are computed, not AI-invented"
      className={`inline-flex items-center gap-1 rounded-md bg-[#eef3fd] px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.07em] text-[#2f6fed] ${className}`}
    >
      <Sparkles className="h-2.5 w-2.5" aria-hidden />
      AI
    </span>
  );
}

function bundleLabel(value: string) {
  return value.replace(/[☀️🔋♨️🚗]/gu, "").trim();
}

function financeTermMonths(rec: Recommendation) {
  const assumption = rec.assumptions.find((a) => a.field === "financing_term_months");
  const parsed = assumption?.value.match(/\d+/)?.[0];
  return parsed ? Number(parsed) : 180;
}

function monthsToYears(months: number) {
  const years = months / 12;
  return Number.isInteger(years) ? `${years} years` : `${years.toFixed(1)} years`;
}

function tierScenario(rec: Recommendation, tier: Tier) {
  return (
    rec.alternatives.find((alt) => alt.scenario_id === tier.scenario_id) ??
    rec.alternatives.find((alt) => alt.scenario_id === rec.best.scenario_id) ??
    rec.best
  );
}

function tierIcon(id: Tier["id"]) {
  if (id === "low") return Sun;
  if (id === "middle") return Flame;
  return BatteryCharging;
}

function bucketRows(scenario: ScenarioResult) {
  return [
    { label: "Electricity", value: scenario.breakdown.electricity_eur_month, icon: Sun },
    { label: "Heating", value: scenario.breakdown.heating_eur_month, icon: Flame },
    { label: "Mobility", value: scenario.breakdown.mobility_eur_month, icon: PlugZap },
  ];
}

function savingTone(n: number) {
  return n >= 0 ? "text-[#047857]" : "text-[#b45309]";
}

/* The engine names its uncertainty drivers and resolved assumptions with machine
   keys (e.g. "hp_subsidy", "specific_yield_kwh_per_kwp"). Those must never reach
   the customer raw — map the known ones to plain English, and title-case any
   unmapped key as a graceful fallback. */
const DRIVER_LABELS: Record<string, string> = {
  irradiance: "Local solar irradiance",
  "local irradiance": "Local solar irradiance",
  dynamic_spread: "Dynamic tariff spread",
  "dynamic tariff spread": "Dynamic tariff spread",
  hp_subsidy: "Heat-pump subsidy rate",
  "kfw subsidy rate": "KfW subsidy rate",
  autarky: "Self-consumption ratio",
  "self-consumption ratio": "Self-consumption ratio",
};

const ASSUMPTION_LABELS: Record<string, string> = {
  // Google Solar / roof
  roof_area_usable_m2: "Usable roof area",
  pv_system_kwp: "PV system size",
  panel_count: "Solar panels",
  roof_orientation: "Roof orientation",
  specific_yield_kwh_per_kwp: "Roof solar yield",
  // Energy prices
  retail_price_eur_kwh: "Grid electricity price",
  grid_fee_eur_kwh: "Local grid fee",
  dynamic_spread_eur_kwh: "Dynamic tariff spread",
  petrol_per_litre_eur: "Petrol price",
  diesel_per_litre_eur: "Diesel price",
  public_charge_per_kwh_eur: "Public charging price",
  // Physics defaults
  autarky_pv_only: "Self-consumption (PV only)",
  autarky_with_battery: "Self-consumption (PV + battery)",
  battery_capacity_kwh: "Battery capacity",
  battery_sizing_heuristic: "Battery sizing method",
  heat_pump_cop: "Heat pump efficiency",
  petrol_consumption_l_per_100km: "Petrol consumption",
  diesel_consumption_l_per_100km: "Diesel consumption",
  ev_consumption_kwh_per_100km: "EV consumption",
  annual_consumption_kwh: "Annual electricity use",
  pv_sizing_heuristic: "PV sizing method",
  // Subsidies
  kfw_subsidy_rate: "KfW 458 subsidy",
  kfw_458_hp_subsidy: "KfW 458 heat-pump grant",
  kfw_hp_subsidy: "KfW 458 heat-pump grant",
  vat_exemption_pv: "PV VAT exemption",
  // Permit checks
  denkmal_listed: "Heritage listing check",
  permit_monument_zone: "Heritage zone check",
  permit_bebauungsplan: "Development plan check",
  private_parking: "Private parking check",
  mastr_neighbour_count: "Neighbouring PV systems",
  // Financing & location
  financing_apr: "Financing APR",
  financing_term_months: "Financing term",
  climate_zone: "Climate zone",
};

function titleCase(key: string) {
  return key
    .replace(/[_-]+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function driverLabel(raw: string) {
  return DRIVER_LABELS[raw.trim().toLowerCase()] ?? titleCase(raw);
}

function assumptionLabel(field: string) {
  return ASSUMPTION_LABELS[field] ?? titleCase(field);
}

/* What the AI layer actually ran, distilled from the live pipeline (Google Solar
   roof model, the German permit checks, the resolved subsidy programmes). Derived
   purely from the streamed run — returns null fields when a stage didn't run, so
   the section degrades to the Recommendation-only evidence on the skip-to-offers
   path. Numbers come straight from the stream; nothing is invented here. */
interface AiEvidence {
  roof: string | null;
  permits: { value: string; tone: "ok" | "warn" } | null;
  subsidies: { value: string; source: string } | null;
}

function aiEvidenceFrom(groups: StageGroup[]): AiEvidence {
  const by = (id: StageGroup["id"]) => groups.find((g) => g.id === id);

  const solar = by("solar")?.solar ?? null;
  const roof = solar
    ? `${solar.kwp} kWp · ${solar.panels} panels · ${solar.orientation} @ ${solar.tiltDeg}°`
    : null;

  const permitStage = by("permit");
  const permitRows = (permitStage?.events ?? []).filter((e) => e.category);
  const permits = permitRows.length
    ? (() => {
        const total = permitRows.length;
        const caution = permitRows.filter((e) => e.status === "warn").length;
        return {
          value: caution
            ? `${total} checks · ${total - caution} clear, ${caution} caution`
            : `${total} checks · all clear`,
          tone: caution ? ("warn" as const) : ("ok" as const),
        };
      })()
    : null;

  const subs = by("subsidy")?.subsidies ?? null;
  const subsidies = subs?.grants.length
    ? {
        value:
          subs.totalEur > 0
            ? `${subs.grants.length} programmes · ${eur(subs.totalEur)} off capex`
            : `${subs.grants.length} programmes applied`,
        source: [...new Set(subs.grants.map((g) => g.source))].join(" · "),
      }
    : null;

  return { roof, permits, subsidies };
}

export default function OfferResultPage({
  rec,
  onBack,
  events = [],
  run,
  address,
}: {
  rec: Recommendation;
  onBack: () => void;
  events?: ActivityEvent[];
  run?: PipelineRunState;
  /** Full address string for the PDF cover page, e.g. "Musterstraße 12, Berlin". */
  address?: string;
}) {
  const best = rec.best;
  const financeMonths = financeTermMonths(rec);
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);

  // Distil the live run into headline evidence. Absent on the skip-to-offers
  // path → the section falls back to the Recommendation's own capex + drivers.
  const ai = run ? aiEvidenceFrom(groupEventsByStage(events, run)) : null;
  const subsidyCard = ai?.subsidies ?? {
    value:
      best.capex.subsidy_eur > 0
        ? `${eur(best.capex.subsidy_eur)} off capex`
        : "0% VAT applied",
    source: best.capex.subsidy_note,
  };

  async function handlePdfDownload() {
    setGeneratingPdf(true);
    setPdfError(null);
    try {
      // Fetch LLM-generated narrative sections; fall back to empty array if backend is unreachable
      let sections: import("@/lib/api").ReportSection[] = [];
      try {
        sections = await postReport(rec, address);
      } catch {
        // Backend unavailable (demo/offline mode) — PDF still generates with stub layout
      }

      const { generatePdfBlob } = await import("./NarrativePdf");
      const blob = await generatePdfBlob(rec, sections, address);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "heimwende-energy-advisory-report.pdf";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      // Revoke after a short delay so the browser can open the download
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (err) {
      setPdfError(err instanceof Error ? err.message : "PDF generation failed");
    } finally {
      setGeneratingPdf(false);
    }
  }

  return (
    <main className="relative min-h-screen bg-[#f6f8fc] text-[#0f172a]">
      {/* Decorative grid — mirrors landing page texture */}
      <div aria-hidden className="offer-grid pointer-events-none fixed inset-0" />

      <header className="sticky top-0 z-20 border-b border-[#e7eaf0] bg-white/85 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-[1000px] items-center justify-between px-5">
          {/* Brand */}
          <div className="flex items-center gap-2.5">
            <HeimwendeMark size={26} className="rounded-md shadow-[0_2px_8px_-2px_rgb(47_111_237/0.4)]" />
            <span className="text-[15px] font-bold tracking-[-0.02em] text-[#0f172a]">Heimwende</span>
          </div>
          {/* Back */}
          <button
            type="button"
            onClick={onBack}
            className={`inline-flex h-9 items-center gap-2 rounded-lg px-2 text-[13px] font-semibold text-[#64748b] transition-[background-color,color,transform] duration-150 ${EASE} hover:bg-[#f1f4f9] hover:text-[#0f172a] active:scale-[0.97]`}
          >
            <ArrowLeft size={16} strokeWidth={2.2} />
            Back to model
          </button>
        </div>
      </header>

      <div className="relative z-10 mx-auto max-w-[1000px] space-y-6 px-5 py-8 sm:py-10">
        {/* ── Page title ───────────────────────────────────────────────── */}
        <div className="offer-rise pb-2" style={{ animationDelay: "0ms" }}>
          <h1 className="text-[40px] font-extrabold leading-[0.95] tracking-[-0.04em] text-[#0f172a] sm:text-[56px]">
            Your Energy Plan
          </h1>
        </div>

        {/* ── Choose a package ─────────────────────────────────────────── */}
        <Section title="Choose your package" delay={80}>
          <div className="grid items-start gap-4 lg:grid-cols-3">
            {rec.tiers.map((tier, index) => (
              <TierCard
                key={tier.id}
                tier={tier}
                scenario={tierScenario(rec, tier)}
                financeMonths={financeMonths}
                index={index}
              />
            ))}
          </div>
        </Section>

        {/* ── What we checked ──────────────────────────────────────────── */}
        <Section title="What we checked" delay={140}>
          <div className="grid gap-3 sm:grid-cols-2">
            <Evidence
              icon={Database}
              label="Baseline spend"
              value={`${eur(rec.current_monthly_spend_eur)}/mo today`}
            />
            {ai?.roof && (
              <Evidence icon={Sun} label="Roof analysis" value={ai.roof} note="Google Solar" />
            )}
            {ai?.permits && (
              <Evidence
                icon={ListChecks}
                label="Permit checks"
                value={ai.permits.value}
                note="Live German building rules"
                tone={ai.permits.tone}
              />
            )}
            <Evidence
              icon={BadgeEuro}
              label="Subsidies applied"
              value={subsidyCard.value}
              note={subsidyCard.source}
            />
            <Evidence
              icon={Globe2}
              label="Biggest driver"
              value={driverLabel(best.confidence.biggest_driver)}
              note="Largest swing in the confidence band"
            />
            <Evidence
              icon={ShieldCheck}
              label="Confidence range"
              value={`${eur(best.confidence.low_eur)} to ${eur(best.confidence.high_eur)}/mo`}
              note={`± ${eur(best.confidence.band_eur)}/mo`}
            />
          </div>
        </Section>

        {/* ── Data & assumptions ───────────────────────────────────────── */}
        {rec.assumptions.length > 0 && (
          <section className="offer-rise" style={{ animationDelay: "200ms" }}>
            <SourceList assumptions={rec.assumptions} />
          </section>
        )}

        {/* ── Advisor letter ───────────────────────────────────────────── */}
        <Section title="Personal advisor recommendation letter" delay={260}>
          <article className="overflow-hidden rounded-2xl border border-[#e7eaf0] bg-white shadow-[0_18px_50px_-30px_rgb(15_23_42/0.2)]">
            {/* Letterhead */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#eef1f6] bg-[#fafbfe] px-6 py-3.5 sm:px-8">
              <div className="flex items-center gap-2.5">
                <HeimwendeMark size={28} className="rounded-lg shadow-[0_4px_12px_-4px_rgb(47_111_237/0.5)]" />
                <div>
                  <p className="text-[13px] font-semibold tracking-[-0.01em] text-[#0f172a]">
                    Heimwende <span className="text-[#94a3b8]">×</span> Cloover
                  </p>
                  <p className="text-[11px] font-medium text-[#94a3b8]">Home Energy Advisory</p>
                </div>
              </div>
              <p className="inline-flex items-center gap-1.5 text-[11px] font-medium tabular-nums text-[#94a3b8]">
                <MapPin size={11} strokeWidth={2.2} />
                Berlin · {LETTER_DATE}
              </p>
            </div>

            {/* Body — one serif voice, italic throughout, no bold. */}
            <div
              className="px-6 py-6 italic text-[15px] leading-[1.75] text-[#334155] sm:px-8"
              style={{ fontFamily: LETTER_FONT }}
            >
              <p>Dear homeowner,</p>

              <Markdown className="mt-3 max-w-[62ch] space-y-3">
                {`${rec.proposal_copy_md}\n\n${rec.upsell.reason_md}`.replace(/\*+/g, "")}
              </Markdown>

              {/* Sign-off */}
              <div className="mt-5">
                <p>Warm regards,</p>
                <p
                  className="-mb-1 mt-0.5 text-[28px] leading-none text-[#0f172a]"
                  style={{ fontFamily: SIGNATURE_FONT }}
                >
                  Heimwende
                </p>
                <div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-0.5">
                  <span className="text-[13px] text-[#0f172a]">Your Heimwende Advisor</span>
                  <AiBadge />
                  <span className="text-[12px] font-medium text-[#94a3b8]">
                    · Every figure is computed, not AI-invented.
                  </span>
                </div>
              </div>
            </div>
          </article>
        </Section>

        {/* ── Continue / export ────────────────────────────────────────── */}
        <section
          className="offer-rise flex flex-col gap-5 rounded-2xl border border-[#d4e0fb] bg-gradient-to-br from-[#eef3fd] to-[#e2ebfb] p-7 sm:flex-row sm:items-center sm:justify-between"
          style={{ animationDelay: "320ms" }}
        >
          <div>
            <p className="text-[17px] font-semibold tracking-[-0.01em] text-[#0f172a]">Ready to continue</p>
            <p className="mt-1 text-[13px] font-medium text-[#64748b]">
              Lock in the recommended package or export the customer packet.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <a
              href="https://www.cloover.com/kontakt"
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#2f6fed] px-5 text-[13px] font-semibold text-white shadow-[0_8px_20px_-6px_rgb(47_111_237/0.6)] transition-[background-color,transform] duration-150 ${EASE} hover:bg-[#2862da] active:scale-[0.97]`}
            >
              Continue offer
              <ChevronRight size={16} strokeWidth={2.3} />
            </a>
            <button
              type="button"
              onClick={handlePdfDownload}
              disabled={generatingPdf}
              className={`inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[#e7eaf0] bg-white px-5 text-[13px] font-semibold text-[#334155] transition-[background-color,transform] duration-150 ${EASE} hover:bg-[#f1f5f9] active:scale-[0.97] disabled:opacity-60 disabled:cursor-not-allowed`}
            >
              {generatingPdf ? (
                <>
                  <Loader2 size={16} strokeWidth={2.2} className="animate-spin" />
                  Generating…
                </>
              ) : (
                <>
                  <Download size={16} strokeWidth={2.2} />
                  Download PDF
                </>
              )}
            </button>
          </div>
          {pdfError && (
            <p className="w-full text-[12px] font-medium text-[#dc2626]">
              PDF error: {pdfError}
            </p>
          )}
        </section>
      </div>
    </main>
  );
}

function Section({
  title,
  delay,
  children,
}: {
  title: string;
  delay: number;
  children: React.ReactNode;
}) {
  return (
    <section className="offer-rise" style={{ animationDelay: `${delay}ms` }}>
      <h2 className="mb-3 text-[13px] font-semibold uppercase tracking-[0.12em] text-[#94a3b8]">
        {title}
      </h2>
      {children}
    </section>
  );
}

function Evidence({
  icon: Icon,
  label,
  value,
  note,
  tone = "default",
}: {
  icon: LucideIcon;
  label: string;
  value: string;
  /** Small muted provenance / detail line under the value (e.g. the source). */
  note?: string;
  /** Colours the value: green "all clear" or amber "caution" for check results. */
  tone?: "default" | "ok" | "warn";
}) {
  const valueTone =
    tone === "ok"
      ? "text-[#047857] font-medium"
      : tone === "warn"
        ? "text-[#b45309] font-medium"
        : "text-[#475569]";
  return (
    <div className="flex gap-3.5 rounded-xl border border-[#e7eaf0] bg-white p-4">
      <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#eef3fd] text-[#2f6fed]">
        <Icon size={17} strokeWidth={2.1} />
      </div>
      <div className="min-w-0">
        <p className="text-[13px] font-semibold text-[#0f172a]">{label}</p>
        <p className={`mt-0.5 text-[13px] leading-5 ${valueTone}`}>{clean(value)}</p>
        {note && <p className="mt-1 text-[11px] leading-4 text-[#94a3b8]">{clean(note)}</p>}
      </div>
    </div>
  );
}

/* The provenance ledger: every resolved assumption the engine used, with its
   official source (PVGIS, Destatis/BNetzA, KfW 458, MaStR …). These already ride
   on the Recommendation but the offer page never surfaced them — this is the
   honest "we checked the real data, here's where it came from" receipt. */
/* Collapsed by default to the first PREVIEW_COUNT rows — the full list is long,
   technical provenance the customer rarely needs. A "show all / fold up" toggle
   reveals the rest in place. */
const SOURCE_PREVIEW_COUNT = 2;

function SourceList({ assumptions }: { assumptions: Assumption[] }) {
  const [expanded, setExpanded] = useState(false);
  const collapsible = assumptions.length > SOURCE_PREVIEW_COUNT;
  const visible = expanded || !collapsible ? assumptions : assumptions.slice(0, SOURCE_PREVIEW_COUNT);
  const hiddenCount = assumptions.length - SOURCE_PREVIEW_COUNT;

  return (
    <div className="mt-3 rounded-xl border border-[#e7eaf0] bg-white p-4 sm:p-5">
      <p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.1em] text-[#94a3b8]">
        Data &amp; assumptions
      </p>
      <dl className="divide-y divide-[#eef1f6]">
        {visible.map((a) => (
          <div
            key={a.field}
            className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-0.5 py-2.5"
          >
            <dt className="text-[13px] font-medium text-[#334155]">{assumptionLabel(a.field)}</dt>
            <dd className="text-[13px] font-semibold tabular-nums text-[#0f172a]">
              {clean(a.value)}
            </dd>
            <p className="w-full text-[11px] leading-4 text-[#94a3b8]">{clean(a.source)}</p>
          </div>
        ))}
      </dl>
      {collapsible && (
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          className={`mt-2 flex w-full items-center justify-center gap-1.5 rounded-lg border-t border-[#eef1f6] pt-2.5 text-[12px] font-semibold text-[#64748b] transition-[color,transform] duration-150 ${EASE} hover:text-[#2f6fed] active:scale-[0.99]`}
        >
          {expanded ? (
            <>
              Fold up
              <ChevronDown size={14} strokeWidth={2.6} className="rotate-180" />
            </>
          ) : (
            <>
              <span className="tracking-[0.2em] text-[#94a3b8]">···</span>
              Show all {assumptions.length} assumptions
              <span className="text-[#94a3b8]">(+{hiddenCount})</span>
              <ChevronDown size={14} strokeWidth={2.6} />
            </>
          )}
        </button>
      )}
    </div>
  );
}

/* Staircase ("Treppe") offsets — each card is pushed down less than the one to
   its left, so the row rises to the right and the recommended "future-proof"
   card stands highest. Only on lg+ where the three sit side by side. */
const TIER_STEP = ["lg:mt-20", "lg:mt-10", "lg:mt-0"];

function TierCard({
  tier,
  scenario,
  financeMonths,
  index,
}: {
  tier: Tier;
  scenario: ScenarioResult;
  financeMonths: number;
  index: number;
}) {
  const Icon = tierIcon(tier.id);
  const recommended = tier.id === "high";

  return (
    <div
      className={`offer-rise relative ${TIER_STEP[index] ?? "lg:mt-0"}`}
      style={{ animationDelay: `${160 + index * 70}ms` }}
    >
      {recommended && (
        <div
          aria-hidden
          className="pointer-events-none absolute -inset-5 rounded-[34px] bg-[radial-gradient(closest-side,rgba(47,111,237,0.55),rgba(47,111,237,0.18)_55%,transparent_82%)] blur-2xl"
        />
      )}
      <article
        className={`group relative flex h-full flex-col rounded-2xl border bg-white p-5 transition-[transform,box-shadow,border-color] duration-200 ${EASE} [@media(hover:hover)]:hover:-translate-y-0.5 [@media(hover:hover)]:hover:shadow-[0_18px_40px_-22px_rgb(15_23_42/0.28)] ${
          recommended
            ? "border-[#2f6fed] shadow-[0_0_0_1px_rgb(47_111_237/0.3),0_24px_50px_-24px_rgb(47_111_237/0.55)]"
            : "border-[#e7eaf0] shadow-[0_12px_30px_-14px_rgb(15_23_42/0.25)]"
        }`}
      >
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef3fd] text-[#2f6fed]">
            <Icon size={18} strokeWidth={2.1} />
          </div>
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#94a3b8]">
              {tier.name}
            </p>
            <h3 className="mt-0.5 text-[15px] font-semibold leading-tight text-[#0f172a]">
              {bundleLabel(tier.label)}
            </h3>
          </div>
        </div>
        {recommended && (
          <span className="shrink-0 rounded-full bg-[#2f6fed] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.06em] text-white shadow-[0_4px_12px_-3px_rgb(47_111_237/0.6)]">
            Recommended
          </span>
        )}
      </div>

      <div className="mt-5 flex items-end gap-2">
        <span className="text-[44px] font-bold leading-none tracking-[-0.03em] tabular-nums text-[#047857]">
          {eur(tier.saving_after_payoff_eur)}
        </span>
        <span className="pb-1 text-[13px] font-medium text-[#94a3b8]">/mo</span>
      </div>
      <p className="mt-2 text-[12px] font-medium text-[#64748b]">
        <span className={`font-semibold tabular-nums ${savingTone(tier.installment_eur_month)}`}>
          {eur(tier.installment_eur_month, { sign: true })}/mo
        </span>{" "}
        after payoff · from now{" "}
        <span className={`font-semibold tabular-nums ${savingTone(tier.monthly_saving_eur)}`}>
          {eur(tier.monthly_saving_eur, { sign: true })}/mo
        </span>{" "}
        net
      </p>

      <div className="mt-5 grid grid-cols-3 gap-2">
        {bucketRows(scenario).map((bucket) => {
          const BucketIcon = bucket.icon;
          return (
            <div key={bucket.label} className="rounded-lg bg-[#f6f8fc] p-2.5">
              <BucketIcon size={14} strokeWidth={2.1} className="text-[#94a3b8]" />
              <p className="mt-2 text-[10px] font-medium uppercase tracking-[0.04em] text-[#94a3b8]">
                {bucket.label}
              </p>
              <p className="text-[13px] font-semibold text-[#0f172a] tabular-nums">{eur(bucket.value)}</p>
            </div>
          );
        })}
      </div>

      <p className="mt-5 flex-1 text-[13px] leading-6 text-[#64748b]">
        <AiBadge className="mr-1.5 align-[1px]" />
        {clean(tier.rationale_md)}
      </p>

      <div className="mt-5 flex items-center justify-between border-t border-[#e7eaf0] pt-3.5">
        <span className="text-[12px] font-medium text-[#94a3b8]">after {monthsToYears(financeMonths)}</span>
        <span className="text-[12px] font-semibold text-[#0f172a] tabular-nums">
          {eur(tier.installment_eur_month, { sign: true })}/mo financing
        </span>
      </div>
      </article>
    </div>
  );
}
